apiVersion: apps/v1
kind: Deployment
metadata:
  name: codecruncher
  namespace: codecruncher
  labels:
    app: codecruncher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codecruncher
  template:
    metadata:
      labels:
        app: codecruncher
    spec:
      containers:
        - name: codecruncher
          image: 809312053369.dkr.ecr.ap-south-1.amazonaws.com/codecruncher:v1
          ports:
            - containerPort: 80
