apiVersion: v1
kind: Service
metadata:
  name: codecruncher-service
  namespace: codecruncher
spec:
  selector:
    app: codecruncher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
